ALTER USER 'root'@'localhost' IDENTIFIED BY 'uFakEt5rwkTl1adjfg';
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'cm'@'localhost' IDENTIFIED BY 'uQ8nstTMYAa6XAaf';
DROP USER IF EXISTS ''@'localhost';
DROP DATABASE IF EXISTS test;
FLUSH PRIVILEGES;
